version: "2"

services:
  scraper:
    build: ./scraper
    volumes:
      - ./scraper:/scraper
    ports:
      - "4000:4000"
  app:
    build: ./app
    volumes:
      - ./app:/app
    ports:
      - "3000:3000"
  back:
    build: ./back
    volumes:
      - ./back:/code
    ports:
      - "5000:5000"
    links:
      - db
  db:
    image: mongo:3.0
    volumes:
      - ./data/db:/data/db
